spin_manifest_version = 2

[application]
authors = ["mizchi"]
name = "spin-wagi-demo"
version = "0.1.0"
description = "MoonBit WASIp2 component on Spin HTTP trigger (WAGI executor)"

[[trigger.http]]
route = "/..."
executor = { type = "wagi" }
component = "spin-wagi"

[component.spin-wagi]
source = "component.wasm"
